export const LOAD_JOBS_FROM_MARKET = "LOAD JOBS FROM MARKET";

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SET_SIGNUP_REDIRECT_PATH = 'SET_SIGNUP_REDIRECT_PATH';

export const UPDATE_USER_PERSONAL_START = 'UPDATE_USER_PERSONAL_START';
export const UPDATE_USER_PERSONAL_SUCCESS = 'UPDATE_USER_PERSONAL_SUCCESS';
export const UPDATE_USER_PERSONAL_FAIL = 'UPDATE_USER_PERSONAL_FAIL';

export const GET_USER_PERSONAL_START = 'GET_USER_PERSONAL_START';
export const GET_USER_PERSONAL_SUCCESS = 'GET_USER_PERSONAL_SUCCESS';
export const GET_USER_PERSONAL_FAIL = 'GET_USER_PERSONAL_FAIL';

export const UPDATE_USER_PROFILE_START = 'UPDATE_USER_PROFILE_START';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

export const GET_FREELANCER_PROFILE_START = 'GET_FREELANCER_PROFILE_START';
export const GET_FREELANCER_PROFILE_SUCCESS = 'GET_FREELANCER_PROFILE_SUCCESS';
export const GET_FREELANCER_PROFILE_FAIL = 'GET_FREELANCER_PROFILE_FAIL';

export const USER_ACCOUNT_ACTIVATE_START = "USER_ACCOUNT_ACTIVATE_START";
export const USER_ACCOUNT_ACTIVATE_FAIL = 'USER_ACCOUNT_ACTIVATE_FAIL';
export const USER_ACCOUNT_ACTIVATE_SUCCESS = 'USER_ACCOUNT_ACTIVATE_SUCCESS';

export const RESET_FORGOT_USER_PASSWORD_START = "RESET_FORGOT_USER_PASSWORD_START";
export const RESET_FORGOT_USER_PASSWORD_FAIL = 'RESET_FORGOT_USER_PASSWORD_FAIL';
export const RESET_FORGOT_USER_PASSWORD_SUCCESS = 'RESET_FORGOT_USER_PASSWORD_SUCCESS';

// Client Actions
export const UPDATE_CLIENT_PUBLIC_PROFILE_START = 'UPDATE_CLIENT_PUBLIC_PROFILE_START';
export const UPDATE_CLIENT_PUBLIC_PROFILE_SUCCESS = 'UPDATE_CLIENT_PUBLIC_PROFILE_SUCCESS';
export const UPDATE_CLIENT_PUBLIC_PROFILE_FAIL = 'UPDATE_CLIENT_PUBLIC_PROFILE_FAIL';

export const GET_CLIENT_PUBLIC_PROFILE_START = 'GET_CLIENT_PUBLIC_PROFILE_START';
export const GET_CLIENT_PUBLIC_PROFILE_SUCCESS = 'GET_CLIENT_PUBLIC_PROFILE_SUCCESS';
export const GET_CLIENT_PUBLIC_PROFILE_FAIL = 'GET_CLIENT_PUBLIC_PROFILE_FAIL';

export const GET_CLIENT_PROFILE_START = 'GET_CLIENT_PROFILE_START';
export const GET_CLIENT_PROFILE_SUCCESS = 'GET_CLIENT_PROFILE_SUCCESS';
export const GET_CLIENT_PROFILE_FAIL = 'GET_CLIENT_PROFILE_FAIL';

// Job Actions
export const POST_CLIENT_JOB_START = "POST_CLIENT_JOB_START";
export const POST_CLIENT_JOB_SUCCESS = "POST_CLIENT_JOB_SUCCESS";
export const POST_CLIENT_JOB_FAIL = "POST_CLIENT_JOB_FAIL";

export const GET_FREELANCE_MARKET_JOBS_START = "GET_FREELANCE_MARKET_JOBS_START";
export const GET_FREELANCE_MARKET_JOBS_SUCCESS = "GET_FREELANCE_MARKET_JOBS_SUCCESS";
export const GET_FREELANCE_MARKET_JOBS_FAIL = "GET_FREELANCE_MARKET_JOBS_FAIL";

export const GET_JOB_DATA_TO_SUBMIT_PROPOSAL_START = "GET_JOB_DATA_TO_SUBMIT_PROPOSAL_START";
export const GET_JOB_DATA_TO_SUBMIT_PROPOSAL_SUCCESS = "GET_JOB_DATA_TO_SUBMIT_PROPOSAL_SUCCESS";
export const GET_JOB_DATA_TO_SUBMIT_PROPOSAL_FAIL = "GET_JOB_DATA_TO_SUBMIT_PROPOSAL_FAIL";

export const SUBMIT_PROPOSAL_FOR_JOB_START = "SUBMIT_PROPOSAL_FOR_JOB_START";
export const SUBMIT_PROPOSAL_FOR_JOB_SUCCESS = "SUBMIT_PROPOSAL_FOR_JOB_SUCCESS";
export const SUBMIT_PROPOSAL_FOR_JOB_FAIL = "SUBMIT_PROPOSAL_FOR_JOB_FAIL";

export const GET_CLIENT_JOBS_CREATED_REPORT_START = "GET_CLIENT_JOBS_CREATED_REPORT_START";
export const GET_CLIENT_JOBS_CREATED_REPORT_SUCCESS = "GET_CLIENT_JOBS_CREATED_REPORT_SUCCESS";
export const GET_CLIENT_JOBS_CREATED_REPORT_FAIL = "GET_CLIENT_JOBS_CREATED_REPORT_FAIL";

export const GET_PROPOSALS_RECEIVED_FOR_JOB_LIST_START = "GET_PROPOSALS_RECEIVED_FOR_JOB_LIST_START";
export const GET_PROPOSALS_RECEIVED_FOR_JOB_LIST_SUCCESS = "GET_PROPOSALS_RECEIVED_FOR_JOB_LIST_SUCCESS";
export const GET_PROPOSALS_RECEIVED_FOR_JOB_LIST_FAIL = "GET_PROPOSALS_RECEIVED_FOR_JOB_LIST_FAIL";

export const GET_FULL_JOB_POST_FOR_FREELANCER_START = "GET_FULL_JOB_POST_FOR_FREELANCER_START";
export const GET_FULL_JOB_POST_FOR_FREELANCER_SUCCESS = "GET_FULL_JOB_POST_FOR_FREELANCER_SUCCESS";
export const GET_FULL_JOB_POST_FOR_FREELANCER_FAIL = "GET_FULL_JOB_POST_FOR_FREELANCER_FAIL";

export const GET_FULL_JOB_POST_FOR_CLIENT_START = "GET_FULL_JOB_POST_FOR_CLIENT_START";
export const GET_FULL_JOB_POST_FOR_CLIENT_SUCCESS = "GET_FULL_JOB_POST_FOR_CLIENT_SUCCESS";
export const GET_FULL_JOB_POST_FOR_CLIENT_FAIL = "GET_FULL_JOB_POST_FOR_CLIENT_FAIL";

export const GET_FULL_PROPOSAL_RECEIVED_FOR_JOB_START = "GET_FULL_PROPOSAL_RECEIVED_FOR_JOB_START";
export const GET_FULL_PROPOSAL_RECEIVED_FOR_JOB_SUCCESS = "GET_FULL_PROPOSAL_RECEIVED_FOR_JOB_SUCCESS";
export const GET_FULL_PROPOSAL_RECEIVED_FOR_JOB_FAIL = "GET_FULL_PROPOSAL_RECEIVED_FOR_JOB_FAIL";

// User Profile Picture Update
export const UPDATE_USER_PROFILE_PICTURE_START = "UPDATE_USER_PROFILE_PICTURE_START";
export const UPDATE_USER_PROFILE_PICTURE_SUCCESS = "UPDATE_USER_PROFILE_PICTURE_SUCCESS";
export const UPDATE_USER_PROFILE_PICTURE_FAIL = "UPDATE_USER_PROFILE_PICTURE_FAIL";

// JOBPROPOSALS SUBMITTED BY FERELANCER
export const GET_JOBPROPOSALS_SUBMITTED_BY_FERELANCER_START = "GET_JOBPROPOSALS_SUBMITTED_BY_FERELANCER_START";
export const GET_JOBPROPOSALS_SUBMITTED_BY_FERELANCER_SUCCESS = "GET_JOBPROPOSALS_SUBMITTED_BY_FERELANCER_SUCCESS";
export const GET_JOBPROPOSALS_SUBMITTED_BY_FERELANCER_FAIL = "GET_JOBPROPOSALS_SUBMITTED_BY_FERELANCER_FAIL";

// SINGLE JOBPROPOSAL WITH JOB SUBMITTED BY FERELANCER
export const GET_FULL_JOB_PROPOSAL_AND_JOB_FOR_FERELANCER_START = "GET_FULL_JOB_PROPOSAL_AND_JOB_FOR_FERELANCER_START";
export const GET_FULL_JOB_PROPOSAL_AND_JOB_FOR_FERELANCER_SUCCESS = "GET_FULL_JOB_PROPOSAL_AND_JOB_FOR_FERELANCER_SUCCESS";
export const GET_FULL_JOB_PROPOSAL_AND_JOB_FOR_FERELANCER_FAIL = "GET_FULL_JOB_PROPOSAL_AND_JOB_FOR_FERELANCER_FAIL";

// GET MARKET FREELANCERS LIST
export const GET_MARKET_FERELANCERS_START = "GET_MARKET_FERELANCERS_START";
export const GET_MARKET_FERELANCERS_SUCCESS = "GET_MARKET_FERELANCERS_SUCCESS";
export const GET_MARKET_FERELANCERS_FAIL = "GET_MARKET_FERELANCERS_FAIL";