// Get Users List For Admin Dashboard
export const GET_USERS_LIST_FOR_ADMIN_DASHBOARD_START = "GET_USERS_LIST_FOR_ADMIN_DASHBOARD_START";
export const GET_USERS_LIST_FOR_ADMIN_DASHBOARD_SUCCESS = "GET_USERS_LIST_FOR_ADMIN_DASHBOARD_SUCCESS";
export const GET_USERS_LIST_FOR_ADMIN_DASHBOARD_FAIL = "GET_USERS_LIST_FOR_ADMIN_DASHBOARD_FAIL";