version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 6000
      runas: ubuntu
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 6000
      runas: ubuntu
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
  